include:
  - project: 'mthreads-ci-templates'
    ref: 'master'
    files:
      - '.base.yml'
      - '.install-musa.yml'

variables:
  MUSA_PATH: "/usr/local/musa/bin"

.build-tilelang_musa-base:
  extends: ".k8s-base"
  needsSourceCode:
    fetch: true
    submodules: false
  timeout: 60m
  variables:
    MUSA_PATH: "${MUSA_PATH:-/usr/local/musa/bin}"
    K8S_IMAGE: "sh-harbor.mthreads.com/os-build/mt-build:develop"
    GIT_SUBMODULE_STRATEGY: none

.gpu-tilelang_musa-base:
  extends: ".k8s-gpu-base"
  needsSourceCode:
    fetch: true
    submodules: false
  execution:
    nodeSelector:
      GPU_TYPE: 'S5000'
      DDK_VERSION: 'master'
  variables:
    MUSA_PATH: "${MUSA_PATH:-/usr/local/musa/bin}"
    K8S_IMAGE: "sh-harbor.mthreads.com/tilelang-ci-smoke/tilelang_musa:20260518-torch-20260609"
    GIT_SUBMODULE_STRATEGY: none

smoke-ci-test:
  extends:
    - ".gpu-tilelang_musa-base"
    - ".install-musa"
  timeout: 120m
  variables:
    MUSA_MODULE: "MUSATOOLKITS,MUSARUNTIME,MTCC,MUDNN,MCCL"
  withCredentials:
    - type: git
      id: sh-code
  script:
    - "export WORKSPACE=${WORKSPACE:-$(pwd)}"
    - "export REPO_DIR=${WORKSPACE}/$(basename \"$PWD\")"
    - "test -f /usr/lib/x86_64-linux-gnu/libmusa.so.1"
    - "cd ${REPO_DIR}"
    - "echo 'Cloning submodules in main repository (non-recursive)...'"
    - "git submodule update --init"
    - "echo 'Entering 3rdparty/tvm and cloning its submodules...'"
    - "cd 3rdparty/tvm"
    - "git submodule update --init"
    - "echo 'Entering 3rdparty/tvm_ffi and manually cloning dlpack and libbacktrace...'"
    - "cd 3rdparty/tvm-ffi"
    - "git config submodule.3rdparty/dlpack.url git@sh-code.mthreads.com:mirror/github.com/dmlc/dlpack.git"
    - "git config submodule.3rdparty/libbacktrace.url git@sh-code.mthreads.com:mirror/github.com/ianlancetaylor/libbacktrace.git"
    - "git submodule update --init"
    - "cd ${REPO_DIR}"
    - "export USE_MUSA=1"
    - "python3 -m build --wheel -C cmake.define.USE_ALTERNATIVE_LINKER=OFF"
    - "export LD_LIBRARY_PATH=${REPO_DIR}/build/lib:$LD_LIBRARY_PATH"
    - "python3 -m pip install --force-reinstall -i https://pypi.tuna.tsinghua.edu.cn/simple dist/*.whl"
    - "python3 -c \"import tilelang; print('tilelang', tilelang.__version__, tilelang.__file__)\""
    - "python3 -m pip install -r requirements-test.txt -i https://pypi.tuna.tsinghua.edu.cn/simple"
    - "python3 -m pip install pytest-timeout -i https://pypi.tuna.tsinghua.edu.cn/simple"
    - "bash testing/run_test.sh ci_smoke -vv -s --tb=short --durations=20 --timeout=60 --timeout-method=thread"
