[pytest]
addopts = --ignore=python/cache --ignore=python/carver --ignore=python/cpu --ignore=python/autotune
    --ignore=python/kernel/test_tilelang_kernel_bf16_gemm_mma.py
    --ignore=python/kernel/test_tilelang_kernel_fp8_gemm_mma.py
    --ignore=python/kernel/test_tilelang_kernel_gemm_mma_intrinsic.py
    --ignore=python/kernel/test_tilelang_kernel_int4_gemm_mma.py
    --ignore=python/language/test_tilelang_language_cooperative.py
    --ignore=python/language/test_tilelang_language_pdl.py
    --ignore=python/language/test_tilelang_language_cluster.py
    --ignore=python/language/test_tilelang_language_ldg.py
    --ignore=python/language/test_tilelang_language_stg.py
    --ignore=python/language/test_tilelang_language_async_copy_gemm_sm80.py
    --ignore=python/language/test_tilelang_language_intrinsics_codegen.py
    --ignore=python/transform/test_tilelang_transform_lower_ldgstg.py
markers =
    gpu: mark test as requiring GPU runtime.
    rocm: mark test as requiring ROCm runtime.
    llvm: mark test as requiring LLVM runtime.
    cuda: mark test as requiring CUDA runtime.
    musa: mark test as requiring MUSA runtime.
