[pytest]
addopts = --import-mode=importlib
markers =
    gpu: mark test as requiring GPU runtime.
    rocm: mark test as requiring ROCm runtime.
    llvm: mark test as requiring LLVM runtime.
    cuda: mark test as requiring CUDA runtime.
    musa: mark test as requiring MUSA runtime.
